### PR TITLE
Rails 7.1 support

### PR DESCRIPTION
**Pull request by cpgo**
Just bumped the `activerecord` version and fixed a minor change related to the `default_timezone` setter.

Taking a closer look at rails 7.1 release notes but as far as I could find there are no more changes needed.

### CODE REVIEW

**Comment by EugZol** [comment]
@cpgo Please rebase to allow tests to run (updated in the master)

**Comment by cpgo** [comment]
@EugZol done

**Comment by EugZol** [comment]
@cpgo sure!

**Comment by cpgo** [comment]
Changed the version check to look at `activerecord` version instead of `rails`.
Tests are passing locally, not sure why the CI is breaking, will take a better look later

**Comment by EugZol** [comment]
Seems it should be the other way around :)

**Comment by cpgo** [comment]
Yep :upside_down_face: 
But I see some weird UTF encoding errors on my CI run now

**Comment by EugZol** [comment]
https://github.com/EugZol/where_exists/pull/28

**Comment by EugZol** [comment]
@cpgo Pushed the new gem version. Thank you!

**Pull request closed without merging**
