### PR TITLE
Allow modifying the condition query via a given block

### PR DESCRIPTION
**Pull request by apauly**
I've added support for modifying the condition query by passing a block.

E.g. something like this:

```
User.where_exists(:posts) {|posts|
  posts.published.where(created_at: 2.days.ago..Time.now)
}
```

I've added a new tests. All tests are passing.

### CODE REVIEW

**Comment by EugZol** [comment]
Hello @apauly. Looks great! Would you kindly rebase, taking into account new changes (there was a merge of bugfix of deeply nested associations)?

**Comment by apauly** [comment]
Hi @EugZol,
sure, will take a look at this.

**Comment by apauly** [comment]
@EugZol Rebase done. Would love to see this merged. Please let me know if you have anything else in mind.

**Comment by EugZol** [comment]
@apauly Looks good. Thank you very much!

**Pull request merged**
